export type CustomerStatus =
  | "Active"
  | "Paused"
  | "Inactive";

export type Customer = {
  customerNumber: string;
  firstName: string;
  surname: string;
  fullName: string;
  address: string;
  postcode: string;
  email: string;
  homePhone: string;
  mobilePhone: string;
  lawnSize: number;
  groupNumber: number;
  treatmentPrice: number;
  status: CustomerStatus;
  vanNumber: number;
  nextVisit: string;
  lastVisit: string;
  lockedGate: boolean;
  dogOnProperty: boolean;
  preferredContact:
    | "SMS"
    | "Email"
    | "Telephone";
  notes: string;
};

export const demoCustomers: Customer[] = [
  {
    customerNumber: "1001",
    firstName: "Oliver",
    surname: "Smith",
    fullName: "Oliver Smith",
    address: "3 Oak Avenue, Ainsdale",
    postcode: "PR8 2AA",
    email: "oliver.smith1001@example.com",
    homePhone: "01704 555000",
    mobilePhone: "07700 900000",
    lawnSize: 60,
    groupNumber: 1,
    treatmentPrice: 22,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1002",
    firstName: "Amelia",
    surname: "Brown",
    fullName: "Amelia Brown",
    address: "10 Crescent Avenue, Ainsdale",
    postcode: "PR8 2BH",
    email: "amelia.brown1002@example.com",
    homePhone: "",
    mobilePhone: "07700 900001",
    lawnSize: 97,
    groupNumber: 1,
    treatmentPrice: 25,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1003",
    firstName: "George",
    surname: "Evans",
    fullName: "George Evans",
    address: "17 Liverpool Road, Ainsdale",
    postcode: "PR8 2CO",
    email: "george.evans1003@example.com",
    homePhone: "",
    mobilePhone: "07700 900002",
    lawnSize: 134,
    groupNumber: 1,
    treatmentPrice: 29,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Telephone",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1004",
    firstName: "Isla",
    surname: "Roberts",
    fullName: "Isla Roberts",
    address: "24 Orchard View, Ainsdale",
    postcode: "PR8 2DB",
    email: "isla.roberts1004@example.com",
    homePhone: "01704 555003",
    mobilePhone: "07700 900003",
    lawnSize: 171,
    groupNumber: 1,
    treatmentPrice: 32,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1005",
    firstName: "Harry",
    surname: "Thompson",
    fullName: "Harry Thompson",
    address: "31 Oak Avenue, Ainsdale",
    postcode: "PR8 2EI",
    email: "harry.thompson1005@example.com",
    homePhone: "",
    mobilePhone: "07700 900004",
    lawnSize: 208,
    groupNumber: 1,
    treatmentPrice: 36,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1006",
    firstName: "Ava",
    surname: "Edwards",
    fullName: "Ava Edwards",
    address: "38 Mill Lane, Birkdale",
    postcode: "PR8 3FP",
    email: "ava.edwards1006@example.com",
    homePhone: "",
    mobilePhone: "07700 900005",
    lawnSize: 245,
    groupNumber: 2,
    treatmentPrice: 39,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1007",
    firstName: "Jack",
    surname: "Lewis",
    fullName: "Jack Lewis",
    address: "45 Roe Lane, Birkdale",
    postcode: "PR8 3GC",
    email: "jack.lewis1007@example.com",
    homePhone: "01704 555006",
    mobilePhone: "07700 900006",
    lawnSize: 282,
    groupNumber: 2,
    treatmentPrice: 43,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1008",
    firstName: "Mia",
    surname: "Jones",
    fullName: "Mia Jones",
    address: "52 Moor Lane, Birkdale",
    postcode: "PR8 3HJ",
    email: "mia.jones1008@example.com",
    homePhone: "",
    mobilePhone: "07700 900007",
    lawnSize: 319,
    groupNumber: 2,
    treatmentPrice: 46,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Email",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1009",
    firstName: "Charlie",
    surname: "Wilson",
    fullName: "Charlie Wilson",
    address: "59 Church Road, Birkdale",
    postcode: "PR8 3IQ",
    email: "charlie.wilson1009@example.com",
    homePhone: "",
    mobilePhone: "07700 900008",
    lawnSize: 356,
    groupNumber: 2,
    treatmentPrice: 50,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1010",
    firstName: "Grace",
    surname: "Thomas",
    fullName: "Grace Thomas",
    address: "66 Mill Lane, Birkdale",
    postcode: "PR8 3JD",
    email: "grace.thomas1010@example.com",
    homePhone: "01704 555009",
    mobilePhone: "07700 900009",
    lawnSize: 393,
    groupNumber: 2,
    treatmentPrice: 53,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1011",
    firstName: "Thomas",
    surname: "Walker",
    fullName: "Thomas Walker",
    address: "73 Balmoral Drive, Southport",
    postcode: "PR9 4KK",
    email: "thomas.walker1011@example.com",
    homePhone: "",
    mobilePhone: "07700 900010",
    lawnSize: 430,
    groupNumber: 3,
    treatmentPrice: 57,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1012",
    firstName: "Sophie",
    surname: "White",
    fullName: "Sophie White",
    address: "80 Coronation Road, Southport",
    postcode: "PR9 4LR",
    email: "sophie.white1012@example.com",
    homePhone: "",
    mobilePhone: "07700 900011",
    lawnSize: 467,
    groupNumber: 3,
    treatmentPrice: 60,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1013",
    firstName: "James",
    surname: "Green",
    fullName: "James Green",
    address: "87 Willow Drive, Southport",
    postcode: "PR9 4ME",
    email: "james.green1013@example.com",
    homePhone: "01704 555012",
    mobilePhone: "07700 900012",
    lawnSize: 504,
    groupNumber: 3,
    treatmentPrice: 64,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "SMS",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1014",
    firstName: "Emily",
    surname: "Harris",
    fullName: "Emily Harris",
    address: "3 Freshfield Road, Southport",
    postcode: "PR9 4NL",
    email: "emily.harris1014@example.com",
    homePhone: "",
    mobilePhone: "07700 900013",
    lawnSize: 541,
    groupNumber: 3,
    treatmentPrice: 67,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1015",
    firstName: "William",
    surname: "Taylor",
    fullName: "William Taylor",
    address: "10 Balmoral Drive, Southport",
    postcode: "PR9 4OS",
    email: "william.taylor1015@example.com",
    homePhone: "",
    mobilePhone: "07700 900014",
    lawnSize: 578,
    groupNumber: 3,
    treatmentPrice: 71,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1016",
    firstName: "Ella",
    surname: "Davies",
    fullName: "Ella Davies",
    address: "17 Elm Park, Formby",
    postcode: "L37 5PF",
    email: "ella.davies1016@example.com",
    homePhone: "01704 555015",
    mobilePhone: "07700 900015",
    lawnSize: 74,
    groupNumber: 4,
    treatmentPrice: 23,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1017",
    firstName: "Henry",
    surname: "Johnson",
    fullName: "Henry Johnson",
    address: "24 Manor Close, Formby",
    postcode: "L37 5QM",
    email: "henry.johnson1017@example.com",
    homePhone: "",
    mobilePhone: "07700 900016",
    lawnSize: 111,
    groupNumber: 4,
    treatmentPrice: 27,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1018",
    firstName: "Lucy",
    surname: "Wright",
    fullName: "Lucy Wright",
    address: "31 Cambridge Road, Formby",
    postcode: "L37 5RT",
    email: "lucy.wright1018@example.com",
    homePhone: "",
    mobilePhone: "07700 900017",
    lawnSize: 148,
    groupNumber: 4,
    treatmentPrice: 30,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: true,
    preferredContact: "Telephone",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1019",
    firstName: "Daniel",
    surname: "Hughes",
    fullName: "Daniel Hughes",
    address: "38 College Road, Formby",
    postcode: "L37 5SG",
    email: "daniel.hughes1019@example.com",
    homePhone: "01704 555018",
    mobilePhone: "07700 900018",
    lawnSize: 185,
    groupNumber: 4,
    treatmentPrice: 34,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1020",
    firstName: "Freya",
    surname: "Hall",
    fullName: "Freya Hall",
    address: "45 Elm Park, Formby",
    postcode: "L37 5TN",
    email: "freya.hall1020@example.com",
    homePhone: "",
    mobilePhone: "07700 900019",
    lawnSize: 222,
    groupNumber: 4,
    treatmentPrice: 37,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1021",
    firstName: "Oliver",
    surname: "Smith",
    fullName: "Oliver Smith",
    address: "52 Victoria Gardens, Hightown",
    postcode: "L38 6AA",
    email: "oliver.smith1021@example.com",
    homePhone: "",
    mobilePhone: "07700 900020",
    lawnSize: 259,
    groupNumber: 5,
    treatmentPrice: 41,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1022",
    firstName: "Amelia",
    surname: "Brown",
    fullName: "Amelia Brown",
    address: "59 Sandringham Drive, Hightown",
    postcode: "L38 6BH",
    email: "amelia.brown1022@example.com",
    homePhone: "01704 555021",
    mobilePhone: "07700 900021",
    lawnSize: 296,
    groupNumber: 5,
    treatmentPrice: 44,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1023",
    firstName: "George",
    surname: "Evans",
    fullName: "George Evans",
    address: "66 Meadow Close, Hightown",
    postcode: "L38 6CO",
    email: "george.evans1023@example.com",
    homePhone: "",
    mobilePhone: "07700 900022",
    lawnSize: 333,
    groupNumber: 5,
    treatmentPrice: 48,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Email",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1024",
    firstName: "Isla",
    surname: "Roberts",
    fullName: "Isla Roberts",
    address: "73 Highfield Close, Hightown",
    postcode: "L38 6DB",
    email: "isla.roberts1024@example.com",
    homePhone: "",
    mobilePhone: "07700 900023",
    lawnSize: 370,
    groupNumber: 5,
    treatmentPrice: 51,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1025",
    firstName: "Harry",
    surname: "Thompson",
    fullName: "Harry Thompson",
    address: "80 Victoria Gardens, Hightown",
    postcode: "L38 6EI",
    email: "harry.thompson1025@example.com",
    homePhone: "01704 555024",
    mobilePhone: "07700 900024",
    lawnSize: 407,
    groupNumber: 5,
    treatmentPrice: 55,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1026",
    firstName: "Ava",
    surname: "Edwards",
    fullName: "Ava Edwards",
    address: "87 Liverpool Road, Crosby",
    postcode: "L23 7FP",
    email: "ava.edwards1026@example.com",
    homePhone: "",
    mobilePhone: "07700 900025",
    lawnSize: 444,
    groupNumber: 6,
    treatmentPrice: 58,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1027",
    firstName: "Jack",
    surname: "Lewis",
    fullName: "Jack Lewis",
    address: "3 Orchard View, Crosby",
    postcode: "L23 7GC",
    email: "jack.lewis1027@example.com",
    homePhone: "",
    mobilePhone: "07700 900026",
    lawnSize: 481,
    groupNumber: 6,
    treatmentPrice: 62,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1028",
    firstName: "Mia",
    surname: "Jones",
    fullName: "Mia Jones",
    address: "10 Oak Avenue, Crosby",
    postcode: "L23 7HJ",
    email: "mia.jones1028@example.com",
    homePhone: "01704 555027",
    mobilePhone: "07700 900027",
    lawnSize: 518,
    groupNumber: 6,
    treatmentPrice: 65,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "SMS",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1029",
    firstName: "Charlie",
    surname: "Wilson",
    fullName: "Charlie Wilson",
    address: "17 Crescent Avenue, Crosby",
    postcode: "L23 7IQ",
    email: "charlie.wilson1029@example.com",
    homePhone: "",
    mobilePhone: "07700 900028",
    lawnSize: 555,
    groupNumber: 6,
    treatmentPrice: 69,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1030",
    firstName: "Grace",
    surname: "Thomas",
    fullName: "Grace Thomas",
    address: "24 Liverpool Road, Crosby",
    postcode: "L23 7JD",
    email: "grace.thomas1030@example.com",
    homePhone: "",
    mobilePhone: "07700 900029",
    lawnSize: 592,
    groupNumber: 6,
    treatmentPrice: 72,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1031",
    firstName: "Thomas",
    surname: "Walker",
    fullName: "Thomas Walker",
    address: "31 Moor Lane, Ainsdale",
    postcode: "PR8 8KK",
    email: "thomas.walker1031@example.com",
    homePhone: "01704 555030",
    mobilePhone: "07700 900030",
    lawnSize: 88,
    groupNumber: 7,
    treatmentPrice: 24,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1032",
    firstName: "Sophie",
    surname: "White",
    fullName: "Sophie White",
    address: "38 Church Road, Ainsdale",
    postcode: "PR8 8LR",
    email: "sophie.white1032@example.com",
    homePhone: "",
    mobilePhone: "07700 900031",
    lawnSize: 125,
    groupNumber: 7,
    treatmentPrice: 28,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1033",
    firstName: "James",
    surname: "Green",
    fullName: "James Green",
    address: "45 Mill Lane, Ainsdale",
    postcode: "PR8 8ME",
    email: "james.green1033@example.com",
    homePhone: "",
    mobilePhone: "07700 900032",
    lawnSize: 162,
    groupNumber: 7,
    treatmentPrice: 31,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Telephone",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1034",
    firstName: "Emily",
    surname: "Harris",
    fullName: "Emily Harris",
    address: "52 Roe Lane, Ainsdale",
    postcode: "PR8 8NL",
    email: "emily.harris1034@example.com",
    homePhone: "01704 555033",
    mobilePhone: "07700 900033",
    lawnSize: 199,
    groupNumber: 7,
    treatmentPrice: 35,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1035",
    firstName: "William",
    surname: "Taylor",
    fullName: "William Taylor",
    address: "59 Moor Lane, Ainsdale",
    postcode: "PR8 8OS",
    email: "william.taylor1035@example.com",
    homePhone: "",
    mobilePhone: "07700 900034",
    lawnSize: 236,
    groupNumber: 7,
    treatmentPrice: 38,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1036",
    firstName: "Ella",
    surname: "Davies",
    fullName: "Ella Davies",
    address: "66 Willow Drive, Birkdale",
    postcode: "PR8 1PF",
    email: "ella.davies1036@example.com",
    homePhone: "",
    mobilePhone: "07700 900035",
    lawnSize: 273,
    groupNumber: 8,
    treatmentPrice: 42,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1037",
    firstName: "Henry",
    surname: "Johnson",
    fullName: "Henry Johnson",
    address: "73 Freshfield Road, Birkdale",
    postcode: "PR8 1QM",
    email: "henry.johnson1037@example.com",
    homePhone: "01704 555036",
    mobilePhone: "07700 900036",
    lawnSize: 310,
    groupNumber: 8,
    treatmentPrice: 45,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1038",
    firstName: "Lucy",
    surname: "Wright",
    fullName: "Lucy Wright",
    address: "80 Balmoral Drive, Birkdale",
    postcode: "PR8 1RT",
    email: "lucy.wright1038@example.com",
    homePhone: "",
    mobilePhone: "07700 900037",
    lawnSize: 347,
    groupNumber: 8,
    treatmentPrice: 49,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: true,
    preferredContact: "Email",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1039",
    firstName: "Daniel",
    surname: "Hughes",
    fullName: "Daniel Hughes",
    address: "87 Coronation Road, Birkdale",
    postcode: "PR8 1SG",
    email: "daniel.hughes1039@example.com",
    homePhone: "",
    mobilePhone: "07700 900038",
    lawnSize: 384,
    groupNumber: 8,
    treatmentPrice: 52,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1040",
    firstName: "Freya",
    surname: "Hall",
    fullName: "Freya Hall",
    address: "3 Willow Drive, Birkdale",
    postcode: "PR8 1TN",
    email: "freya.hall1040@example.com",
    homePhone: "01704 555039",
    mobilePhone: "07700 900039",
    lawnSize: 421,
    groupNumber: 8,
    treatmentPrice: 56,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1041",
    firstName: "Oliver",
    surname: "Smith",
    fullName: "Oliver Smith",
    address: "10 Cambridge Road, Southport",
    postcode: "PR9 2AA",
    email: "oliver.smith1041@example.com",
    homePhone: "",
    mobilePhone: "07700 900040",
    lawnSize: 458,
    groupNumber: 9,
    treatmentPrice: 60,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1042",
    firstName: "Amelia",
    surname: "Brown",
    fullName: "Amelia Brown",
    address: "17 College Road, Southport",
    postcode: "PR9 2BH",
    email: "amelia.brown1042@example.com",
    homePhone: "",
    mobilePhone: "07700 900041",
    lawnSize: 495,
    groupNumber: 9,
    treatmentPrice: 63,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1043",
    firstName: "George",
    surname: "Evans",
    fullName: "George Evans",
    address: "24 Elm Park, Southport",
    postcode: "PR9 2CO",
    email: "george.evans1043@example.com",
    homePhone: "01704 555042",
    mobilePhone: "07700 900042",
    lawnSize: 532,
    groupNumber: 9,
    treatmentPrice: 67,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "SMS",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1044",
    firstName: "Isla",
    surname: "Roberts",
    fullName: "Isla Roberts",
    address: "31 Manor Close, Southport",
    postcode: "PR9 2DB",
    email: "isla.roberts1044@example.com",
    homePhone: "",
    mobilePhone: "07700 900043",
    lawnSize: 569,
    groupNumber: 9,
    treatmentPrice: 70,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1045",
    firstName: "Harry",
    surname: "Thompson",
    fullName: "Harry Thompson",
    address: "38 Cambridge Road, Southport",
    postcode: "PR9 2EI",
    email: "harry.thompson1045@example.com",
    homePhone: "",
    mobilePhone: "07700 900044",
    lawnSize: 65,
    groupNumber: 9,
    treatmentPrice: 22,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1046",
    firstName: "Ava",
    surname: "Edwards",
    fullName: "Ava Edwards",
    address: "45 Meadow Close, Formby",
    postcode: "L37 3FP",
    email: "ava.edwards1046@example.com",
    homePhone: "01704 555045",
    mobilePhone: "07700 900045",
    lawnSize: 102,
    groupNumber: 10,
    treatmentPrice: 26,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1047",
    firstName: "Jack",
    surname: "Lewis",
    fullName: "Jack Lewis",
    address: "52 Highfield Close, Formby",
    postcode: "L37 3GC",
    email: "jack.lewis1047@example.com",
    homePhone: "",
    mobilePhone: "07700 900046",
    lawnSize: 139,
    groupNumber: 10,
    treatmentPrice: 29,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1048",
    firstName: "Mia",
    surname: "Jones",
    fullName: "Mia Jones",
    address: "59 Victoria Gardens, Formby",
    postcode: "L37 3HJ",
    email: "mia.jones1048@example.com",
    homePhone: "",
    mobilePhone: "07700 900047",
    lawnSize: 176,
    groupNumber: 10,
    treatmentPrice: 33,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Telephone",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1049",
    firstName: "Charlie",
    surname: "Wilson",
    fullName: "Charlie Wilson",
    address: "66 Sandringham Drive, Formby",
    postcode: "L37 3IQ",
    email: "charlie.wilson1049@example.com",
    homePhone: "01704 555048",
    mobilePhone: "07700 900048",
    lawnSize: 213,
    groupNumber: 10,
    treatmentPrice: 36,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1050",
    firstName: "Grace",
    surname: "Thomas",
    fullName: "Grace Thomas",
    address: "73 Meadow Close, Formby",
    postcode: "L37 3JD",
    email: "grace.thomas1050@example.com",
    homePhone: "",
    mobilePhone: "07700 900049",
    lawnSize: 250,
    groupNumber: 10,
    treatmentPrice: 40,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1051",
    firstName: "Thomas",
    surname: "Walker",
    fullName: "Thomas Walker",
    address: "80 Oak Avenue, Hightown",
    postcode: "L38 4KK",
    email: "thomas.walker1051@example.com",
    homePhone: "",
    mobilePhone: "07700 900050",
    lawnSize: 287,
    groupNumber: 11,
    treatmentPrice: 43,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1052",
    firstName: "Sophie",
    surname: "White",
    fullName: "Sophie White",
    address: "87 Crescent Avenue, Hightown",
    postcode: "L38 4LR",
    email: "sophie.white1052@example.com",
    homePhone: "01704 555051",
    mobilePhone: "07700 900051",
    lawnSize: 324,
    groupNumber: 11,
    treatmentPrice: 47,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1053",
    firstName: "James",
    surname: "Green",
    fullName: "James Green",
    address: "3 Liverpool Road, Hightown",
    postcode: "L38 4ME",
    email: "james.green1053@example.com",
    homePhone: "",
    mobilePhone: "07700 900052",
    lawnSize: 361,
    groupNumber: 11,
    treatmentPrice: 50,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Email",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1054",
    firstName: "Emily",
    surname: "Harris",
    fullName: "Emily Harris",
    address: "10 Orchard View, Hightown",
    postcode: "L38 4NL",
    email: "emily.harris1054@example.com",
    homePhone: "",
    mobilePhone: "07700 900053",
    lawnSize: 398,
    groupNumber: 11,
    treatmentPrice: 54,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1055",
    firstName: "William",
    surname: "Taylor",
    fullName: "William Taylor",
    address: "17 Oak Avenue, Hightown",
    postcode: "L38 4OS",
    email: "william.taylor1055@example.com",
    homePhone: "01704 555054",
    mobilePhone: "07700 900054",
    lawnSize: 435,
    groupNumber: 11,
    treatmentPrice: 57,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1056",
    firstName: "Ella",
    surname: "Davies",
    fullName: "Ella Davies",
    address: "24 Mill Lane, Crosby",
    postcode: "L23 5PF",
    email: "ella.davies1056@example.com",
    homePhone: "",
    mobilePhone: "07700 900055",
    lawnSize: 472,
    groupNumber: 12,
    treatmentPrice: 61,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1057",
    firstName: "Henry",
    surname: "Johnson",
    fullName: "Henry Johnson",
    address: "31 Roe Lane, Crosby",
    postcode: "L23 5QM",
    email: "henry.johnson1057@example.com",
    homePhone: "",
    mobilePhone: "07700 900056",
    lawnSize: 509,
    groupNumber: 12,
    treatmentPrice: 64,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1058",
    firstName: "Lucy",
    surname: "Wright",
    fullName: "Lucy Wright",
    address: "38 Moor Lane, Crosby",
    postcode: "L23 5RT",
    email: "lucy.wright1058@example.com",
    homePhone: "01704 555057",
    mobilePhone: "07700 900057",
    lawnSize: 546,
    groupNumber: 12,
    treatmentPrice: 68,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: true,
    preferredContact: "SMS",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1059",
    firstName: "Daniel",
    surname: "Hughes",
    fullName: "Daniel Hughes",
    address: "45 Church Road, Crosby",
    postcode: "L23 5SG",
    email: "daniel.hughes1059@example.com",
    homePhone: "",
    mobilePhone: "07700 900058",
    lawnSize: 583,
    groupNumber: 12,
    treatmentPrice: 71,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1060",
    firstName: "Freya",
    surname: "Hall",
    fullName: "Freya Hall",
    address: "52 Mill Lane, Crosby",
    postcode: "L23 5TN",
    email: "freya.hall1060@example.com",
    homePhone: "",
    mobilePhone: "07700 900059",
    lawnSize: 79,
    groupNumber: 12,
    treatmentPrice: 24,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1061",
    firstName: "Oliver",
    surname: "Smith",
    fullName: "Oliver Smith",
    address: "59 Balmoral Drive, Ainsdale",
    postcode: "PR8 6AA",
    email: "oliver.smith1061@example.com",
    homePhone: "01704 555060",
    mobilePhone: "07700 900060",
    lawnSize: 116,
    groupNumber: 13,
    treatmentPrice: 27,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1062",
    firstName: "Amelia",
    surname: "Brown",
    fullName: "Amelia Brown",
    address: "66 Coronation Road, Ainsdale",
    postcode: "PR8 6BH",
    email: "amelia.brown1062@example.com",
    homePhone: "",
    mobilePhone: "07700 900061",
    lawnSize: 153,
    groupNumber: 13,
    treatmentPrice: 31,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1063",
    firstName: "George",
    surname: "Evans",
    fullName: "George Evans",
    address: "73 Willow Drive, Ainsdale",
    postcode: "PR8 6CO",
    email: "george.evans1063@example.com",
    homePhone: "",
    mobilePhone: "07700 900062",
    lawnSize: 190,
    groupNumber: 13,
    treatmentPrice: 34,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Telephone",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1064",
    firstName: "Isla",
    surname: "Roberts",
    fullName: "Isla Roberts",
    address: "80 Freshfield Road, Ainsdale",
    postcode: "PR8 6DB",
    email: "isla.roberts1064@example.com",
    homePhone: "01704 555063",
    mobilePhone: "07700 900063",
    lawnSize: 227,
    groupNumber: 13,
    treatmentPrice: 38,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1065",
    firstName: "Harry",
    surname: "Thompson",
    fullName: "Harry Thompson",
    address: "87 Balmoral Drive, Ainsdale",
    postcode: "PR8 6EI",
    email: "harry.thompson1065@example.com",
    homePhone: "",
    mobilePhone: "07700 900064",
    lawnSize: 264,
    groupNumber: 13,
    treatmentPrice: 41,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1066",
    firstName: "Ava",
    surname: "Edwards",
    fullName: "Ava Edwards",
    address: "3 Elm Park, Birkdale",
    postcode: "PR8 7FP",
    email: "ava.edwards1066@example.com",
    homePhone: "",
    mobilePhone: "07700 900065",
    lawnSize: 301,
    groupNumber: 14,
    treatmentPrice: 45,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1067",
    firstName: "Jack",
    surname: "Lewis",
    fullName: "Jack Lewis",
    address: "10 Manor Close, Birkdale",
    postcode: "PR8 7GC",
    email: "jack.lewis1067@example.com",
    homePhone: "01704 555066",
    mobilePhone: "07700 900066",
    lawnSize: 338,
    groupNumber: 14,
    treatmentPrice: 48,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1068",
    firstName: "Mia",
    surname: "Jones",
    fullName: "Mia Jones",
    address: "17 Cambridge Road, Birkdale",
    postcode: "PR8 7HJ",
    email: "mia.jones1068@example.com",
    homePhone: "",
    mobilePhone: "07700 900067",
    lawnSize: 375,
    groupNumber: 14,
    treatmentPrice: 52,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Email",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1069",
    firstName: "Charlie",
    surname: "Wilson",
    fullName: "Charlie Wilson",
    address: "24 College Road, Birkdale",
    postcode: "PR8 7IQ",
    email: "charlie.wilson1069@example.com",
    homePhone: "",
    mobilePhone: "07700 900068",
    lawnSize: 412,
    groupNumber: 14,
    treatmentPrice: 55,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1070",
    firstName: "Grace",
    surname: "Thomas",
    fullName: "Grace Thomas",
    address: "31 Elm Park, Birkdale",
    postcode: "PR8 7JD",
    email: "grace.thomas1070@example.com",
    homePhone: "01704 555069",
    mobilePhone: "07700 900069",
    lawnSize: 449,
    groupNumber: 14,
    treatmentPrice: 59,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1071",
    firstName: "Thomas",
    surname: "Walker",
    fullName: "Thomas Walker",
    address: "38 Victoria Gardens, Southport",
    postcode: "PR9 8KK",
    email: "thomas.walker1071@example.com",
    homePhone: "",
    mobilePhone: "07700 900070",
    lawnSize: 486,
    groupNumber: 15,
    treatmentPrice: 62,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1072",
    firstName: "Sophie",
    surname: "White",
    fullName: "Sophie White",
    address: "45 Sandringham Drive, Southport",
    postcode: "PR9 8LR",
    email: "sophie.white1072@example.com",
    homePhone: "",
    mobilePhone: "07700 900071",
    lawnSize: 523,
    groupNumber: 15,
    treatmentPrice: 66,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1073",
    firstName: "James",
    surname: "Green",
    fullName: "James Green",
    address: "52 Meadow Close, Southport",
    postcode: "PR9 8ME",
    email: "james.green1073@example.com",
    homePhone: "01704 555072",
    mobilePhone: "07700 900072",
    lawnSize: 560,
    groupNumber: 15,
    treatmentPrice: 69,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "SMS",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1074",
    firstName: "Emily",
    surname: "Harris",
    fullName: "Emily Harris",
    address: "59 Highfield Close, Southport",
    postcode: "PR9 8NL",
    email: "emily.harris1074@example.com",
    homePhone: "",
    mobilePhone: "07700 900073",
    lawnSize: 597,
    groupNumber: 15,
    treatmentPrice: 73,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1075",
    firstName: "William",
    surname: "Taylor",
    fullName: "William Taylor",
    address: "66 Victoria Gardens, Southport",
    postcode: "PR9 8OS",
    email: "william.taylor1075@example.com",
    homePhone: "",
    mobilePhone: "07700 900074",
    lawnSize: 93,
    groupNumber: 15,
    treatmentPrice: 25,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1076",
    firstName: "Ella",
    surname: "Davies",
    fullName: "Ella Davies",
    address: "73 Liverpool Road, Formby",
    postcode: "L37 1PF",
    email: "ella.davies1076@example.com",
    homePhone: "01704 555075",
    mobilePhone: "07700 900075",
    lawnSize: 130,
    groupNumber: 16,
    treatmentPrice: 28,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1077",
    firstName: "Henry",
    surname: "Johnson",
    fullName: "Henry Johnson",
    address: "80 Orchard View, Formby",
    postcode: "L37 1QM",
    email: "henry.johnson1077@example.com",
    homePhone: "",
    mobilePhone: "07700 900076",
    lawnSize: 167,
    groupNumber: 16,
    treatmentPrice: 32,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1078",
    firstName: "Lucy",
    surname: "Wright",
    fullName: "Lucy Wright",
    address: "87 Oak Avenue, Formby",
    postcode: "L37 1RT",
    email: "lucy.wright1078@example.com",
    homePhone: "",
    mobilePhone: "07700 900077",
    lawnSize: 204,
    groupNumber: 16,
    treatmentPrice: 35,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: true,
    preferredContact: "Telephone",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1079",
    firstName: "Daniel",
    surname: "Hughes",
    fullName: "Daniel Hughes",
    address: "3 Crescent Avenue, Formby",
    postcode: "L37 1SG",
    email: "daniel.hughes1079@example.com",
    homePhone: "01704 555078",
    mobilePhone: "07700 900078",
    lawnSize: 241,
    groupNumber: 16,
    treatmentPrice: 39,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1080",
    firstName: "Freya",
    surname: "Hall",
    fullName: "Freya Hall",
    address: "10 Liverpool Road, Formby",
    postcode: "L37 1TN",
    email: "freya.hall1080@example.com",
    homePhone: "",
    mobilePhone: "07700 900079",
    lawnSize: 278,
    groupNumber: 16,
    treatmentPrice: 42,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1081",
    firstName: "Oliver",
    surname: "Smith",
    fullName: "Oliver Smith",
    address: "17 Moor Lane, Hightown",
    postcode: "L38 2AA",
    email: "oliver.smith1081@example.com",
    homePhone: "",
    mobilePhone: "07700 900080",
    lawnSize: 315,
    groupNumber: 17,
    treatmentPrice: 46,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1082",
    firstName: "Amelia",
    surname: "Brown",
    fullName: "Amelia Brown",
    address: "24 Church Road, Hightown",
    postcode: "L38 2BH",
    email: "amelia.brown1082@example.com",
    homePhone: "01704 555081",
    mobilePhone: "07700 900081",
    lawnSize: 352,
    groupNumber: 17,
    treatmentPrice: 49,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1083",
    firstName: "George",
    surname: "Evans",
    fullName: "George Evans",
    address: "31 Mill Lane, Hightown",
    postcode: "L38 2CO",
    email: "george.evans1083@example.com",
    homePhone: "",
    mobilePhone: "07700 900082",
    lawnSize: 389,
    groupNumber: 17,
    treatmentPrice: 53,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Email",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1084",
    firstName: "Isla",
    surname: "Roberts",
    fullName: "Isla Roberts",
    address: "38 Roe Lane, Hightown",
    postcode: "L38 2DB",
    email: "isla.roberts1084@example.com",
    homePhone: "",
    mobilePhone: "07700 900083",
    lawnSize: 426,
    groupNumber: 17,
    treatmentPrice: 56,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1085",
    firstName: "Harry",
    surname: "Thompson",
    fullName: "Harry Thompson",
    address: "45 Moor Lane, Hightown",
    postcode: "L38 2EI",
    email: "harry.thompson1085@example.com",
    homePhone: "01704 555084",
    mobilePhone: "07700 900084",
    lawnSize: 463,
    groupNumber: 17,
    treatmentPrice: 60,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1086",
    firstName: "Ava",
    surname: "Edwards",
    fullName: "Ava Edwards",
    address: "52 Willow Drive, Crosby",
    postcode: "L23 3FP",
    email: "ava.edwards1086@example.com",
    homePhone: "",
    mobilePhone: "07700 900085",
    lawnSize: 500,
    groupNumber: 18,
    treatmentPrice: 64,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1087",
    firstName: "Jack",
    surname: "Lewis",
    fullName: "Jack Lewis",
    address: "59 Freshfield Road, Crosby",
    postcode: "L23 3GC",
    email: "jack.lewis1087@example.com",
    homePhone: "",
    mobilePhone: "07700 900086",
    lawnSize: 537,
    groupNumber: 18,
    treatmentPrice: 67,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1088",
    firstName: "Mia",
    surname: "Jones",
    fullName: "Mia Jones",
    address: "66 Balmoral Drive, Crosby",
    postcode: "L23 3HJ",
    email: "mia.jones1088@example.com",
    homePhone: "01704 555087",
    mobilePhone: "07700 900087",
    lawnSize: 574,
    groupNumber: 18,
    treatmentPrice: 71,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "SMS",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1089",
    firstName: "Charlie",
    surname: "Wilson",
    fullName: "Charlie Wilson",
    address: "73 Coronation Road, Crosby",
    postcode: "L23 3IQ",
    email: "charlie.wilson1089@example.com",
    homePhone: "",
    mobilePhone: "07700 900088",
    lawnSize: 70,
    groupNumber: 18,
    treatmentPrice: 23,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1090",
    firstName: "Grace",
    surname: "Thomas",
    fullName: "Grace Thomas",
    address: "80 Willow Drive, Crosby",
    postcode: "L23 3JD",
    email: "grace.thomas1090@example.com",
    homePhone: "",
    mobilePhone: "07700 900089",
    lawnSize: 107,
    groupNumber: 18,
    treatmentPrice: 26,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Clay soil; monitor drainage after heavy rain.",
  },
  {
    customerNumber: "1091",
    firstName: "Thomas",
    surname: "Walker",
    fullName: "Thomas Walker",
    address: "87 Cambridge Road, Ainsdale",
    postcode: "PR8 4KK",
    email: "thomas.walker1091@example.com",
    homePhone: "01704 555090",
    mobilePhone: "07700 900090",
    lawnSize: 144,
    groupNumber: 19,
    treatmentPrice: 30,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1092",
    firstName: "Sophie",
    surname: "White",
    fullName: "Sophie White",
    address: "3 College Road, Ainsdale",
    postcode: "PR8 4LR",
    email: "sophie.white1092@example.com",
    homePhone: "",
    mobilePhone: "07700 900091",
    lawnSize: 181,
    groupNumber: 19,
    treatmentPrice: 33,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1093",
    firstName: "James",
    surname: "Green",
    fullName: "James Green",
    address: "10 Elm Park, Ainsdale",
    postcode: "PR8 4ME",
    email: "james.green1093@example.com",
    homePhone: "",
    mobilePhone: "07700 900092",
    lawnSize: 218,
    groupNumber: 19,
    treatmentPrice: 37,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "Telephone",
    notes: "Dog may be in the rear garden.",
  },
  {
    customerNumber: "1094",
    firstName: "Emily",
    surname: "Harris",
    fullName: "Emily Harris",
    address: "17 Manor Close, Ainsdale",
    postcode: "PR8 4NL",
    email: "emily.harris1094@example.com",
    homePhone: "01704 555093",
    mobilePhone: "07700 900093",
    lawnSize: 255,
    groupNumber: 19,
    treatmentPrice: 40,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1095",
    firstName: "William",
    surname: "Taylor",
    fullName: "William Taylor",
    address: "24 Cambridge Road, Ainsdale",
    postcode: "PR8 4OS",
    email: "william.taylor1095@example.com",
    homePhone: "",
    mobilePhone: "07700 900094",
    lawnSize: 292,
    groupNumber: 19,
    treatmentPrice: 44,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Established lawn with straightforward access.",
  },
  {
    customerNumber: "1096",
    firstName: "Ella",
    surname: "Davies",
    fullName: "Ella Davies",
    address: "31 Meadow Close, Birkdale",
    postcode: "PR8 5PF",
    email: "ella.davies1096@example.com",
    homePhone: "",
    mobilePhone: "07700 900095",
    lawnSize: 329,
    groupNumber: 20,
    treatmentPrice: 47,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Shaded rear lawn; monitor moss levels.",
  },
  {
    customerNumber: "1097",
    firstName: "Henry",
    surname: "Johnson",
    fullName: "Henry Johnson",
    address: "38 Highfield Close, Birkdale",
    postcode: "PR8 5QM",
    email: "henry.johnson1097@example.com",
    homePhone: "01704 555096",
    mobilePhone: "07700 900096",
    lawnSize: 366,
    groupNumber: 20,
    treatmentPrice: 51,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1098",
    firstName: "Lucy",
    surname: "Wright",
    fullName: "Lucy Wright",
    address: "45 Victoria Gardens, Birkdale",
    postcode: "PR8 5RT",
    email: "lucy.wright1098@example.com",
    homePhone: "",
    mobilePhone: "07700 900097",
    lawnSize: 403,
    groupNumber: 20,
    treatmentPrice: 54,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: true,
    dogOnProperty: true,
    preferredContact: "Email",
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1099",
    firstName: "Daniel",
    surname: "Hughes",
    fullName: "Daniel Hughes",
    address: "52 Sandringham Drive, Birkdale",
    postcode: "PR8 5SG",
    email: "daniel.hughes1099@example.com",
    homePhone: "",
    mobilePhone: "07700 900098",
    lawnSize: 440,
    groupNumber: 20,
    treatmentPrice: 58,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Small front lawn and medium rear lawn.",
  },
  {
    customerNumber: "1100",
    firstName: "Freya",
    surname: "Hall",
    fullName: "Freya Hall",
    address: "59 Meadow Close, Birkdale",
    postcode: "PR8 5TN",
    email: "freya.hall1100@example.com",
    homePhone: "01704 555099",
    mobilePhone: "07700 900099",
    lawnSize: 477,
    groupNumber: 20,
    treatmentPrice: 61,
    status: "Active",
    vanNumber: 1,
    nextVisit: "Not yet scheduled",
    lastVisit: "No previous visit",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "SMS",
    notes: "Clay soil; monitor drainage after heavy rain.",
  }
];