export type CustomerStatus = "Active" | "Paused" | "Inactive";

export type Customer = {
  customerNumber: string;
  firstName: string;
  surname: string;
  fullName: string;
  address: string;
  postcode: string;
  email: string;
  homePhone: string;
  mobilePhone: string;
  lawnSize: number;
  groupNumber: number;
  treatmentPrice: number;
  status: CustomerStatus;
  vanNumber: number;
  nextVisit: string;
  lastVisit: string;
  lockedGate: boolean;
  dogOnProperty: boolean;
  preferredContact: "SMS" | "Email" | "Telephone";
  notes: string;
};

export const demoCustomers: Customer[] = [
  {
    customerNumber: "1001",
    firstName: "John",
    surname: "Smith",
    fullName: "John & Sarah Smith",
    address: "15 Highfield Close, Ainsdale",
    postcode: "PR8 3NL",
    email: "john.smith@example.com",
    homePhone: "01704 555101",
    mobilePhone: "07700 900101",
    lawnSize: 208,
    groupNumber: 7,
    treatmentPrice: 28,
    status: "Active",
    vanNumber: 1,
    nextVisit: "21 June 2028",
    lastVisit: "10 April 2028",
    lockedGate: false,
    dogOnProperty: true,
    preferredContact: "SMS",
    notes: "Clay soil. Recommend scarification next spring.",
  },
  {
    customerNumber: "1002",
    firstName: "Margaret",
    surname: "Wilson",
    fullName: "Margaret Wilson",
    address: "8 Manor Close, Ainsdale",
    postcode: "PR8 3PX",
    email: "margaret.wilson@example.com",
    homePhone: "01704 555102",
    mobilePhone: "07700 900102",
    lawnSize: 145,
    groupNumber: 7,
    treatmentPrice: 24,
    status: "Active",
    vanNumber: 1,
    nextVisit: "21 June 2028",
    lastVisit: "10 April 2028",
    lockedGate: true,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Prefers a printed treatment report and pays by cheque.",
  },
  {
    customerNumber: "1003",
    firstName: "David",
    surname: "Harris",
    fullName: "David Harris",
    address: "42 Church Road, Ainsdale",
    postcode: "PR8 3BJ",
    email: "david.harris@example.com",
    homePhone: "",
    mobilePhone: "07700 900103",
    lawnSize: 320,
    groupNumber: 9,
    treatmentPrice: 38,
    status: "Active",
    vanNumber: 1,
    nextVisit: "23 June 2028",
    lastVisit: "12 April 2028",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Email",
    notes: "Pays by standing order. Aeration completed in spring 2027.",
  },
  {
    customerNumber: "1004",
    firstName: "Emma",
    surname: "Thompson",
    fullName: "Emma Thompson",
    address: "12 Oak Avenue, Formby",
    postcode: "L37 4AB",
    email: "emma.thompson@example.com",
    homePhone: "",
    mobilePhone: "07700 900104",
    lawnSize: 96,
    groupNumber: 4,
    treatmentPrice: 18,
    status: "Active",
    vanNumber: 1,
    nextVisit: "16 June 2028",
    lastVisit: "6 April 2028",
    lockedGate: true,
    dogOnProperty: true,
    preferredContact: "SMS",
    notes: "Gate reminder required. Small dog may be in rear garden.",
  },
  {
    customerNumber: "1005",
    firstName: "Peter",
    surname: "Johnson",
    fullName: "Peter Johnson",
    address: "7 Sandringham Drive, Formby",
    postcode: "L37 6PL",
    email: "peter.johnson@example.com",
    homePhone: "01704 555105",
    mobilePhone: "07700 900105",
    lawnSize: 480,
    groupNumber: 14,
    treatmentPrice: 52,
    status: "Paused",
    vanNumber: 1,
    nextVisit: "Not currently scheduled",
    lastVisit: "14 September 2027",
    lockedGate: false,
    dogOnProperty: false,
    preferredContact: "Telephone",
    notes: "Temporarily paused service for financial reasons.",
  },
];
const additionalDemoCustomerDetails = [
  {
    customerNumber: "1006",
    firstName: "David",
    surname: "Wilson",
    address: "14 Willow Drive, Ainsdale",
    postcode: "PR8 3HT",
    email: "david.wilson@example.com",
    mobilePhone: "07700 901006",
    groupNumber: 3,
    vanNumber: 1,
    lawnSize: 95,
    treatmentPrice: 20,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Small front and rear lawn.",
  },
  {
    customerNumber: "1007",
    firstName: "Sarah",
    surname: "Johnson",
    address: "22 Sandbrook Road, Ainsdale",
    postcode: "PR8 3LU",
    email: "sarah.johnson@example.com",
    mobilePhone: "07700 901007",
    groupNumber: 3,
    vanNumber: 1,
    lawnSize: 160,
    treatmentPrice: 29,
    lockedGate: true,
    dogOnProperty: false,
    notes: "Rear gate should be left unlocked.",
  },
  {
    customerNumber: "1008",
    firstName: "Peter",
    surname: "Evans",
    address: "6 Victoria Gardens, Birkdale",
    postcode: "PR8 2JN",
    email: "peter.evans@example.com",
    mobilePhone: "07700 901008",
    groupNumber: 4,
    vanNumber: 2,
    lawnSize: 310,
    treatmentPrice: 50,
    lockedGate: false,
    dogOnProperty: true,
    notes: "Friendly dog may be in rear garden.",
  },
  {
    customerNumber: "1009",
    firstName: "Helen",
    surname: "Green",
    address: "31 Liverpool Road, Birkdale",
    postcode: "PR8 4AG",
    email: "helen.green@example.com",
    mobilePhone: "07700 901009",
    groupNumber: 5,
    vanNumber: 2,
    lawnSize: 55,
    treatmentPrice: 18,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Minimum treatment price applies.",
  },
  {
    customerNumber: "1010",
    firstName: "Richard",
    surname: "Taylor",
    address: "18 Crescent Avenue, Southport",
    postcode: "PR8 6RA",
    email: "richard.taylor@example.com",
    mobilePhone: "07700 901010",
    groupNumber: 5,
    vanNumber: 2,
    lawnSize: 420,
    treatmentPrice: 62,
    lockedGate: true,
    dogOnProperty: false,
    notes: "Large rear lawn with side access.",
  },
  {
    customerNumber: "1011",
    firstName: "Andrew",
    surname: "Martin",
    address: "7 Elm Park, Churchtown",
    postcode: "PR9 7QF",
    email: "andrew.martin@example.com",
    mobilePhone: "07700 901011",
    groupNumber: 6,
    vanNumber: 3,
    lawnSize: 180,
    treatmentPrice: 31,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Customer prefers morning visits.",
  },
  {
    customerNumber: "1012",
    firstName: "Claire",
    surname: "Hughes",
    address: "42 Mill Lane, Churchtown",
    postcode: "PR9 8BN",
    email: "claire.hughes@example.com",
    mobilePhone: "07700 901012",
    groupNumber: 6,
    vanNumber: 3,
    lawnSize: 250,
    treatmentPrice: 42,
    lockedGate: true,
    dogOnProperty: true,
    notes: "Locked side gate and dog on property.",
  },
  {
    customerNumber: "1013",
    firstName: "Michael",
    surname: "Brown",
    address: "11 Roe Lane, Southport",
    postcode: "PR9 9EB",
    email: "michael.brown@example.com",
    mobilePhone: "07700 901013",
    groupNumber: 7,
    vanNumber: 1,
    lawnSize: 130,
    treatmentPrice: 25,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Front lawn only.",
  },
  {
    customerNumber: "1014",
    firstName: "Janet",
    surname: "Collins",
    address: "29 Cambridge Road, Southport",
    postcode: "PR9 9PR",
    email: "janet.collins@example.com",
    mobilePhone: "07700 901014",
    groupNumber: 7,
    vanNumber: 1,
    lawnSize: 600,
    treatmentPrice: 82,
    lockedGate: true,
    dogOnProperty: false,
    notes: "Large lawn. Reduced square-metre rate applied.",
  },
  {
    customerNumber: "1015",
    firstName: "Brian",
    surname: "White",
    address: "5 Balmoral Drive, Formby",
    postcode: "L37 6EF",
    email: "brian.white@example.com",
    mobilePhone: "07700 901015",
    groupNumber: 8,
    vanNumber: 2,
    lawnSize: 145,
    treatmentPrice: 27,
    lockedGate: false,
    dogOnProperty: true,
    notes: "Dog normally kept indoors during visits.",
  },
  {
    customerNumber: "1016",
    firstName: "Louise",
    surname: "Adams",
    address: "16 Freshfield Road, Formby",
    postcode: "L37 3HW",
    email: "louise.adams@example.com",
    mobilePhone: "07700 901016",
    groupNumber: 8,
    vanNumber: 2,
    lawnSize: 220,
    treatmentPrice: 38,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Front and rear lawns.",
  },
  {
    customerNumber: "1017",
    firstName: "Kevin",
    surname: "Harris",
    address: "39 Victoria Road, Formby",
    postcode: "L37 7AQ",
    email: "kevin.harris@example.com",
    mobilePhone: "07700 901017",
    groupNumber: 9,
    vanNumber: 3,
    lawnSize: 330,
    treatmentPrice: 52,
    lockedGate: true,
    dogOnProperty: false,
    notes: "Gate reminder required before every visit.",
  },
  {
    customerNumber: "1018",
    firstName: "Emma",
    surname: "Parker",
    address: "8 Wicks Lane, Formby",
    postcode: "L37 2YD",
    email: "emma.parker@example.com",
    mobilePhone: "07700 901018",
    groupNumber: 9,
    vanNumber: 3,
    lawnSize: 110,
    treatmentPrice: 22,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Small shaded rear lawn.",
  },
  {
    customerNumber: "1019",
    firstName: "Daniel",
    surname: "Lewis",
    address: "27 Alt Road, Hightown",
    postcode: "L38 0BF",
    email: "daniel.lewis@example.com",
    mobilePhone: "07700 901019",
    groupNumber: 10,
    vanNumber: 1,
    lawnSize: 170,
    treatmentPrice: 30,
    lockedGate: false,
    dogOnProperty: true,
    notes: "Dog warning required.",
  },
  {
    customerNumber: "1020",
    firstName: "Rebecca",
    surname: "Wood",
    address: "10 Thirlmere Road, Hightown",
    postcode: "L38 3RQ",
    email: "rebecca.wood@example.com",
    mobilePhone: "07700 901020",
    groupNumber: 10,
    vanNumber: 1,
    lawnSize: 260,
    treatmentPrice: 43,
    lockedGate: true,
    dogOnProperty: false,
    notes: "Access through locked side gate.",
  },
  {
    customerNumber: "1021",
    firstName: "Chris",
    surname: "Walker",
    address: "46 Moor Lane, Crosby",
    postcode: "L23 2SA",
    email: "chris.walker@example.com",
    mobilePhone: "07700 901021",
    groupNumber: 11,
    vanNumber: 2,
    lawnSize: 480,
    treatmentPrice: 68,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Large established lawn.",
  },
  {
    customerNumber: "1022",
    firstName: "Julie",
    surname: "Young",
    address: "19 Coronation Road, Crosby",
    postcode: "L23 5RE",
    email: "julie.young@example.com",
    mobilePhone: "07700 901022",
    groupNumber: 11,
    vanNumber: 2,
    lawnSize: 140,
    treatmentPrice: 27,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Customer normally works from home.",
  },
  {
    customerNumber: "1023",
    firstName: "Thomas",
    surname: "Hall",
    address: "33 College Road, Crosby",
    postcode: "L23 0RP",
    email: "thomas.hall@example.com",
    mobilePhone: "07700 901023",
    groupNumber: 12,
    vanNumber: 3,
    lawnSize: 205,
    treatmentPrice: 36,
    lockedGate: true,
    dogOnProperty: true,
    notes: "Locked gate and small dog.",
  },
  {
    customerNumber: "1024",
    firstName: "Susan",
    surname: "King",
    address: "12 The Serpentine, Blundellsands",
    postcode: "L23 6TD",
    email: "susan.king@example.com",
    mobilePhone: "07700 901024",
    groupNumber: 12,
    vanNumber: 3,
    lawnSize: 290,
    treatmentPrice: 48,
    lockedGate: false,
    dogOnProperty: false,
    notes: "Two separate lawn areas.",
  },
  {
    customerNumber: "1025",
    firstName: "Mark",
    surname: "Scott",
    address: "25 Hall Road East, Blundellsands",
    postcode: "L23 8TU",
    email: "mark.scott@example.com",
    mobilePhone: "07700 901025",
    groupNumber: 13,
    vanNumber: 1,
    lawnSize: 360,
    treatmentPrice: 56,
    lockedGate: true,
    dogOnProperty: false,
    notes: "Large rear lawn with locked side access.",
  },
];

/*
 * Each new record starts as a copy of the first existing demo customer.
 * This preserves every required Customer field, including fields that may
 * have been added elsewhere in GreenFlow.
 */
const additionalDemoCustomers: Customer[] =
  additionalDemoCustomerDetails.map(
    (details) => ({
      ...demoCustomers[0],
      ...details,

      fullName: `${details.firstName} ${details.surname}`,

      status: "Active",

      lastVisit: "Not yet visited",
      nextVisit: "Not yet scheduled",
    }),
  );

demoCustomers.push(
  ...additionalDemoCustomers,
);